spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # Configuración de la aplicación
  jpa:
    hibernate:
      ddl-auto: update
  # Configuración de la seguridad
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER